name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    name: Build, test, check
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_GEN0SEC_INDEX: sparse+https://crates-internal.g0s.dev/api/v1/crates/
      CARGO_REGISTRIES_GEN0SEC_TOKEN: ${{ secrets.GEN0SEC_CARGO_TOKEN }}
      CARGO_REGISTRIES_GEN0SEC_CREDENTIAL_PROVIDER: cargo:token
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt, clippy
      - name: Cache target
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/git/
            ~/.cargo/registry/
            target/
          key: ${{ runner.os }}-proxy-protocol-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-proxy-protocol
      - run: cargo fmt --check
      - run: cargo test -- --include-ignored
      - run: cargo build
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

